export const correctResponses = [
    "Excellent work! 🎉",
    "You've got it! 👍",
    "Fantastic job! 🌟",
    "That's correct! Keep it up! 💪",
    "You're on fire! 🔥",
    "Bravo! You nailed it! 👏",
    "Spot on! Great work! 🎯",
    "You're a math whiz! 🧠",
    "Correct! You're making great progress! 📈",
    "You've got the right stuff! 🚀",
    "Absolutely right! Well done! 👌",
    "You're crushing it! 💥",
    "Perfect answer! 💯",
    "You're on a roll! 🎳",
    "Correct! You're unstoppable! 🚂",
    "Amazing work! Keep it up! 🌈",
    "You've cracked the code! 🔓",
    "Right on target! 🎯",
    "You're a problem-solving pro! 🏆",
    "Correct! You're mastering this! 🎓"
];

export const incorrectResponses = [
    "Not quite, but you're on the right track! 🌱",
    "Close! Give it another shot. 🎯",
    "Almost there! Keep trying. 💪",
    "Good effort! Let's review this together. 🤝",
    "Don't give up! You're making progress. 🚶‍♂️",
    "Nice try! Let's break it down step by step. 🧗‍♀️",
    "You're getting closer! Keep pushing. 🏃‍♂️",
    "That's not quite it, but you're learning! 📚",
    "Not correct, but your effort is commendable. 👏",
    "Let's try a different approach. You've got this! 🔄",
    "You're building your skills with each attempt. 🏗️",
    "Mistakes are part of learning. Let's try again! 🔁",
    "You're putting in the work. That's what counts! 💼",
    "Not yet, but you're gaining experience. 🌟",
    "Keep at it! Persistence is key. 🔑",
    "You're brave for trying. Let's give it another go! 🦁",
    "Learning takes time. You're on the right path. 🛤️",
    "Your determination is admirable. Let's try once more! 🔨",
    "Every attempt brings you closer to success. 🏅",
    "It's okay to make mistakes. That's how we improve! 🌈"
];